FROM kartoza/geoserver:2.16.2
# TODO: improve resulting docker image size (since based on this initial setup, final size is about 1.9 GB. Too big)
LABEL maintainer="geotekne.argentina@gmail.com"

#
# FONTS for OSM
# 

RUN apt-get update && apt -y install fonts-noto fonts-dejavu unifont fonts-hanazono


